// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// logLikCpp
List logLikCpp(IntegerMatrix& edgeMat, NumericVector& clusterMRCAs, NumericVector& limProbsVec, List& withinTransMatList, List& betweenTransMatList, int numOpenMP, List alignmentBin, uint numTips, uint numLoci, uint withinMatListIndex, uint betweenMatListIndex);
RcppExport SEXP _DMphyClus_logLikCpp(SEXP edgeMatSEXP, SEXP clusterMRCAsSEXP, SEXP limProbsVecSEXP, SEXP withinTransMatListSEXP, SEXP betweenTransMatListSEXP, SEXP numOpenMPSEXP, SEXP alignmentBinSEXP, SEXP numTipsSEXP, SEXP numLociSEXP, SEXP withinMatListIndexSEXP, SEXP betweenMatListIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix& >::type edgeMat(edgeMatSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type clusterMRCAs(clusterMRCAsSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbsVec(limProbsVecSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransMatList(withinTransMatListSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransMatList(betweenTransMatListSEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< List >::type alignmentBin(alignmentBinSEXP);
    Rcpp::traits::input_parameter< uint >::type numTips(numTipsSEXP);
    Rcpp::traits::input_parameter< uint >::type numLoci(numLociSEXP);
    Rcpp::traits::input_parameter< uint >::type withinMatListIndex(withinMatListIndexSEXP);
    Rcpp::traits::input_parameter< uint >::type betweenMatListIndex(betweenMatListIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(logLikCpp(edgeMat, clusterMRCAs, limProbsVec, withinTransMatList, betweenTransMatList, numOpenMP, alignmentBin, numTips, numLoci, withinMatListIndex, betweenMatListIndex));
    return rcpp_result_gen;
END_RCPP
}
// getConvertedAlignment
SEXP getConvertedAlignment(SEXP& equivVector, CharacterMatrix& alignmentAlphaMat);
RcppExport SEXP _DMphyClus_getConvertedAlignment(SEXP equivVectorSEXP, SEXP alignmentAlphaMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type equivVector(equivVectorSEXP);
    Rcpp::traits::input_parameter< CharacterMatrix& >::type alignmentAlphaMat(alignmentAlphaMatSEXP);
    rcpp_result_gen = Rcpp::wrap(getConvertedAlignment(equivVector, alignmentAlphaMat));
    return rcpp_result_gen;
END_RCPP
}
// newBetweenTransProbsLogLik
double newBetweenTransProbsLogLik(SEXP AugTreePointer, List& withinTransProbs, List& newBetweenTransProbs, uint& numOpenMP, uint& newBetweenMatListIndex, NumericVector& limProbs);
RcppExport SEXP _DMphyClus_newBetweenTransProbsLogLik(SEXP AugTreePointerSEXP, SEXP withinTransProbsSEXP, SEXP newBetweenTransProbsSEXP, SEXP numOpenMPSEXP, SEXP newBetweenMatListIndexSEXP, SEXP limProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransProbs(withinTransProbsSEXP);
    Rcpp::traits::input_parameter< List& >::type newBetweenTransProbs(newBetweenTransProbsSEXP);
    Rcpp::traits::input_parameter< uint& >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< uint& >::type newBetweenMatListIndex(newBetweenMatListIndexSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbs(limProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(newBetweenTransProbsLogLik(AugTreePointer, withinTransProbs, newBetweenTransProbs, numOpenMP, newBetweenMatListIndex, limProbs));
    return rcpp_result_gen;
END_RCPP
}
// newWithinTransProbsLogLik
double newWithinTransProbsLogLik(SEXP AugTreePointer, List& newWithinTransProbs, List& betweenTransProbs, uint& numOpenMP, uint& newWithinMatListIndex, NumericVector& limProbs);
RcppExport SEXP _DMphyClus_newWithinTransProbsLogLik(SEXP AugTreePointerSEXP, SEXP newWithinTransProbsSEXP, SEXP betweenTransProbsSEXP, SEXP numOpenMPSEXP, SEXP newWithinMatListIndexSEXP, SEXP limProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< List& >::type newWithinTransProbs(newWithinTransProbsSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransProbs(betweenTransProbsSEXP);
    Rcpp::traits::input_parameter< uint& >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< uint& >::type newWithinMatListIndex(newWithinMatListIndexSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbs(limProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(newWithinTransProbsLogLik(AugTreePointer, newWithinTransProbs, betweenTransProbs, numOpenMP, newWithinMatListIndex, limProbs));
    return rcpp_result_gen;
END_RCPP
}
// withinClusNNIlogLik
List withinClusNNIlogLik(SEXP AugTreePointer, List& withinTransProbs, List& betweenTransProbs, uint& MRCAofClusForNNI, uint& numMovesNNI, uint& numOpenMP, NumericVector& limProbs);
RcppExport SEXP _DMphyClus_withinClusNNIlogLik(SEXP AugTreePointerSEXP, SEXP withinTransProbsSEXP, SEXP betweenTransProbsSEXP, SEXP MRCAofClusForNNISEXP, SEXP numMovesNNISEXP, SEXP numOpenMPSEXP, SEXP limProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransProbs(withinTransProbsSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransProbs(betweenTransProbsSEXP);
    Rcpp::traits::input_parameter< uint& >::type MRCAofClusForNNI(MRCAofClusForNNISEXP);
    Rcpp::traits::input_parameter< uint& >::type numMovesNNI(numMovesNNISEXP);
    Rcpp::traits::input_parameter< uint& >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbs(limProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(withinClusNNIlogLik(AugTreePointer, withinTransProbs, betweenTransProbs, MRCAofClusForNNI, numMovesNNI, numOpenMP, limProbs));
    return rcpp_result_gen;
END_RCPP
}
// betweenClusNNIlogLik
List betweenClusNNIlogLik(SEXP AugTreePointer, List& withinTransProbs, List& betweenTransProbs, NumericVector& clusterMRCAs, uint& numMovesNNI, uint& numOpenMP, NumericVector& limProbs);
RcppExport SEXP _DMphyClus_betweenClusNNIlogLik(SEXP AugTreePointerSEXP, SEXP withinTransProbsSEXP, SEXP betweenTransProbsSEXP, SEXP clusterMRCAsSEXP, SEXP numMovesNNISEXP, SEXP numOpenMPSEXP, SEXP limProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransProbs(withinTransProbsSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransProbs(betweenTransProbsSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type clusterMRCAs(clusterMRCAsSEXP);
    Rcpp::traits::input_parameter< uint& >::type numMovesNNI(numMovesNNISEXP);
    Rcpp::traits::input_parameter< uint& >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbs(limProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(betweenClusNNIlogLik(AugTreePointer, withinTransProbs, betweenTransProbs, clusterMRCAs, numMovesNNI, numOpenMP, limProbs));
    return rcpp_result_gen;
END_RCPP
}
// clusSplitMergeLogLik
double clusSplitMergeLogLik(SEXP AugTreePointer, List& withinTransProbs, List& betweenTransProbs, IntegerVector& clusMRCAsToSplitOrMerge, uint& numOpenMP, NumericVector& limProbs);
RcppExport SEXP _DMphyClus_clusSplitMergeLogLik(SEXP AugTreePointerSEXP, SEXP withinTransProbsSEXP, SEXP betweenTransProbsSEXP, SEXP clusMRCAsToSplitOrMergeSEXP, SEXP numOpenMPSEXP, SEXP limProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransProbs(withinTransProbsSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransProbs(betweenTransProbsSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type clusMRCAsToSplitOrMerge(clusMRCAsToSplitOrMergeSEXP);
    Rcpp::traits::input_parameter< uint& >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbs(limProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(clusSplitMergeLogLik(AugTreePointer, withinTransProbs, betweenTransProbs, clusMRCAsToSplitOrMerge, numOpenMP, limProbs));
    return rcpp_result_gen;
END_RCPP
}
// RestorePreviousConfig
void RestorePreviousConfig(SEXP AugTreePointer, IntegerMatrix& edgeMat, int& withinMatListIndex, int& betweenMatListIndex, bool NNImove, IntegerVector& clusterMRCAs, bool splitMergeMove);
RcppExport SEXP _DMphyClus_RestorePreviousConfig(SEXP AugTreePointerSEXP, SEXP edgeMatSEXP, SEXP withinMatListIndexSEXP, SEXP betweenMatListIndexSEXP, SEXP NNImoveSEXP, SEXP clusterMRCAsSEXP, SEXP splitMergeMoveSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type edgeMat(edgeMatSEXP);
    Rcpp::traits::input_parameter< int& >::type withinMatListIndex(withinMatListIndexSEXP);
    Rcpp::traits::input_parameter< int& >::type betweenMatListIndex(betweenMatListIndexSEXP);
    Rcpp::traits::input_parameter< bool >::type NNImove(NNImoveSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type clusterMRCAs(clusterMRCAsSEXP);
    Rcpp::traits::input_parameter< bool >::type splitMergeMove(splitMergeMoveSEXP);
    RestorePreviousConfig(AugTreePointer, edgeMat, withinMatListIndex, betweenMatListIndex, NNImove, clusterMRCAs, splitMergeMove);
    return R_NilValue;
END_RCPP
}
// finalDeallocate
void finalDeallocate(SEXP AugTreePointer);
RcppExport SEXP _DMphyClus_finalDeallocate(SEXP AugTreePointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    finalDeallocate(AugTreePointer);
    return R_NilValue;
END_RCPP
}
// getMaxMapSizeEstimate
double getMaxMapSizeEstimate(double& allowedSizeInMegs, unsigned int& numRateCats);
RcppExport SEXP _DMphyClus_getMaxMapSizeEstimate(SEXP allowedSizeInMegsSEXP, SEXP numRateCatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type allowedSizeInMegs(allowedSizeInMegsSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type numRateCats(numRateCatsSEXP);
    rcpp_result_gen = Rcpp::wrap(getMaxMapSizeEstimate(allowedSizeInMegs, numRateCats));
    return rcpp_result_gen;
END_RCPP
}
// checkAndCullMap
void checkAndCullMap(SEXP AugTreePointer, unsigned int& allowedNumberOfElements, float& cullProportion, List& withinTransProbs, List& betweenTransProbs, NumericVector& limProbs);
RcppExport SEXP _DMphyClus_checkAndCullMap(SEXP AugTreePointerSEXP, SEXP allowedNumberOfElementsSEXP, SEXP cullProportionSEXP, SEXP withinTransProbsSEXP, SEXP betweenTransProbsSEXP, SEXP limProbsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AugTreePointer(AugTreePointerSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type allowedNumberOfElements(allowedNumberOfElementsSEXP);
    Rcpp::traits::input_parameter< float& >::type cullProportion(cullProportionSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransProbs(withinTransProbsSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransProbs(betweenTransProbsSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbs(limProbsSEXP);
    checkAndCullMap(AugTreePointer, allowedNumberOfElements, cullProportion, withinTransProbs, betweenTransProbs, limProbs);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DMphyClus_logLikCpp", (DL_FUNC) &_DMphyClus_logLikCpp, 11},
    {"_DMphyClus_getConvertedAlignment", (DL_FUNC) &_DMphyClus_getConvertedAlignment, 2},
    {"_DMphyClus_newBetweenTransProbsLogLik", (DL_FUNC) &_DMphyClus_newBetweenTransProbsLogLik, 6},
    {"_DMphyClus_newWithinTransProbsLogLik", (DL_FUNC) &_DMphyClus_newWithinTransProbsLogLik, 6},
    {"_DMphyClus_withinClusNNIlogLik", (DL_FUNC) &_DMphyClus_withinClusNNIlogLik, 7},
    {"_DMphyClus_betweenClusNNIlogLik", (DL_FUNC) &_DMphyClus_betweenClusNNIlogLik, 7},
    {"_DMphyClus_clusSplitMergeLogLik", (DL_FUNC) &_DMphyClus_clusSplitMergeLogLik, 6},
    {"_DMphyClus_RestorePreviousConfig", (DL_FUNC) &_DMphyClus_RestorePreviousConfig, 7},
    {"_DMphyClus_finalDeallocate", (DL_FUNC) &_DMphyClus_finalDeallocate, 1},
    {"_DMphyClus_getMaxMapSizeEstimate", (DL_FUNC) &_DMphyClus_getMaxMapSizeEstimate, 2},
    {"_DMphyClus_checkAndCullMap", (DL_FUNC) &_DMphyClus_checkAndCullMap, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DMphyClus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
