// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// logLikCpp
List logLikCpp(IntegerMatrix& edgeMat, NumericVector& clusterMRCAs, NumericVector& limProbsVec, List& withinTransMatList, List& betweenTransMatList, int numOpenMP, List alignmentBin, uint numTips, uint numLoci);
RcppExport SEXP DMphyClus_logLikCpp(SEXP edgeMatSEXP, SEXP clusterMRCAsSEXP, SEXP limProbsVecSEXP, SEXP withinTransMatListSEXP, SEXP betweenTransMatListSEXP, SEXP numOpenMPSEXP, SEXP alignmentBinSEXP, SEXP numTipsSEXP, SEXP numLociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix& >::type edgeMat(edgeMatSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type clusterMRCAs(clusterMRCAsSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type limProbsVec(limProbsVecSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransMatList(withinTransMatListSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransMatList(betweenTransMatListSEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< List >::type alignmentBin(alignmentBinSEXP);
    Rcpp::traits::input_parameter< uint >::type numTips(numTipsSEXP);
    Rcpp::traits::input_parameter< uint >::type numLoci(numLociSEXP);
    rcpp_result_gen = Rcpp::wrap(logLikCpp(edgeMat, clusterMRCAs, limProbsVec, withinTransMatList, betweenTransMatList, numOpenMP, alignmentBin, numTips, numLoci));
    return rcpp_result_gen;
END_RCPP
}
// getConvertedAlignment
SEXP getConvertedAlignment(SEXP& equivVector, CharacterMatrix& alignmentAlphaMat);
RcppExport SEXP DMphyClus_getConvertedAlignment(SEXP equivVectorSEXP, SEXP alignmentAlphaMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type equivVector(equivVectorSEXP);
    Rcpp::traits::input_parameter< CharacterMatrix& >::type alignmentAlphaMat(alignmentAlphaMatSEXP);
    rcpp_result_gen = Rcpp::wrap(getConvertedAlignment(equivVector, alignmentAlphaMat));
    return rcpp_result_gen;
END_RCPP
}
// getNULLextPointer
SEXP getNULLextPointer();
RcppExport SEXP DMphyClus_getNULLextPointer() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getNULLextPointer());
    return rcpp_result_gen;
END_RCPP
}
// newBetweenTransProbsLogLik
List newBetweenTransProbsLogLik(SEXP ForestPointerVec, List& newBetweenTransProbs, int numOpenMP);
RcppExport SEXP DMphyClus_newBetweenTransProbsLogLik(SEXP ForestPointerVecSEXP, SEXP newBetweenTransProbsSEXP, SEXP numOpenMPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ForestPointerVec(ForestPointerVecSEXP);
    Rcpp::traits::input_parameter< List& >::type newBetweenTransProbs(newBetweenTransProbsSEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    rcpp_result_gen = Rcpp::wrap(newBetweenTransProbsLogLik(ForestPointerVec, newBetweenTransProbs, numOpenMP));
    return rcpp_result_gen;
END_RCPP
}
// newWithinTransProbsLogLik
List newWithinTransProbsLogLik(SEXP ForestPointerVec, List newWithinTransProbs, IntegerVector clusterMRCAs, int numOpenMP);
RcppExport SEXP DMphyClus_newWithinTransProbsLogLik(SEXP ForestPointerVecSEXP, SEXP newWithinTransProbsSEXP, SEXP clusterMRCAsSEXP, SEXP numOpenMPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ForestPointerVec(ForestPointerVecSEXP);
    Rcpp::traits::input_parameter< List >::type newWithinTransProbs(newWithinTransProbsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clusterMRCAs(clusterMRCAsSEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    rcpp_result_gen = Rcpp::wrap(newWithinTransProbsLogLik(ForestPointerVec, newWithinTransProbs, clusterMRCAs, numOpenMP));
    return rcpp_result_gen;
END_RCPP
}
// withinClusNNIlogLik
List withinClusNNIlogLik(SEXP ForestPointerVec, uint MRCAofClusForNNI, uint numMovesNNI, int numOpenMP);
RcppExport SEXP DMphyClus_withinClusNNIlogLik(SEXP ForestPointerVecSEXP, SEXP MRCAofClusForNNISEXP, SEXP numMovesNNISEXP, SEXP numOpenMPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ForestPointerVec(ForestPointerVecSEXP);
    Rcpp::traits::input_parameter< uint >::type MRCAofClusForNNI(MRCAofClusForNNISEXP);
    Rcpp::traits::input_parameter< uint >::type numMovesNNI(numMovesNNISEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    rcpp_result_gen = Rcpp::wrap(withinClusNNIlogLik(ForestPointerVec, MRCAofClusForNNI, numMovesNNI, numOpenMP));
    return rcpp_result_gen;
END_RCPP
}
// betweenClusNNIlogLik
List betweenClusNNIlogLik(SEXP ForestPointerVec, uint numMovesNNI, int numOpenMP, NumericVector& clusterMRCAs);
RcppExport SEXP DMphyClus_betweenClusNNIlogLik(SEXP ForestPointerVecSEXP, SEXP numMovesNNISEXP, SEXP numOpenMPSEXP, SEXP clusterMRCAsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ForestPointerVec(ForestPointerVecSEXP);
    Rcpp::traits::input_parameter< uint >::type numMovesNNI(numMovesNNISEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type clusterMRCAs(clusterMRCAsSEXP);
    rcpp_result_gen = Rcpp::wrap(betweenClusNNIlogLik(ForestPointerVec, numMovesNNI, numOpenMP, clusterMRCAs));
    return rcpp_result_gen;
END_RCPP
}
// clusSplitMergeLogLik
List clusSplitMergeLogLik(SEXP ForestPointerVec, IntegerVector& clusMRCAsToSplitOrMerge, List& withinTransProbsMats, List& betweenTransProbsMats, int numOpenMP);
RcppExport SEXP DMphyClus_clusSplitMergeLogLik(SEXP ForestPointerVecSEXP, SEXP clusMRCAsToSplitOrMergeSEXP, SEXP withinTransProbsMatsSEXP, SEXP betweenTransProbsMatsSEXP, SEXP numOpenMPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ForestPointerVec(ForestPointerVecSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type clusMRCAsToSplitOrMerge(clusMRCAsToSplitOrMergeSEXP);
    Rcpp::traits::input_parameter< List& >::type withinTransProbsMats(withinTransProbsMatsSEXP);
    Rcpp::traits::input_parameter< List& >::type betweenTransProbsMats(betweenTransProbsMatsSEXP);
    Rcpp::traits::input_parameter< int >::type numOpenMP(numOpenMPSEXP);
    rcpp_result_gen = Rcpp::wrap(clusSplitMergeLogLik(ForestPointerVec, clusMRCAsToSplitOrMerge, withinTransProbsMats, betweenTransProbsMats, numOpenMP));
    return rcpp_result_gen;
END_RCPP
}
// copyForestElements
void copyForestElements(bool keepOld, SEXP ForestVecPointer);
RcppExport SEXP DMphyClus_copyForestElements(SEXP keepOldSEXP, SEXP ForestVecPointerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type keepOld(keepOldSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ForestVecPointer(ForestVecPointerSEXP);
    copyForestElements(keepOld, ForestVecPointer);
    return R_NilValue;
END_RCPP
}
