# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikCppToWrap <- function(edgeMat, alignmentMat, limProbsVec, transMatList, numOpenMP, equivVector, alignmentAlphaMat, alignmentBin, childNodeInClusIndic, returnMatIndic, internalFlag) {
    .Call('DMphyClus_logLikCppToWrap', PACKAGE = 'DMphyClus', edgeMat, alignmentMat, limProbsVec, transMatList, numOpenMP, equivVector, alignmentAlphaMat, alignmentBin, childNodeInClusIndic, returnMatIndic, internalFlag)
}

getConvertedAlignmentToWrap <- function(alignmentMat, numStatesCons, numOpenMP, equivVector, alignmentAlphaMat) {
    .Call('DMphyClus_getConvertedAlignmentToWrap', PACKAGE = 'DMphyClus', alignmentMat, numStatesCons, numOpenMP, equivVector, alignmentAlphaMat)
}

redimMultiBinByClus <- function(multiBinByClus) {
    .Call('DMphyClus_redimMultiBinByClus', PACKAGE = 'DMphyClus', multiBinByClus)
}

logLikCppToWrapV <- function(edgeMatList, alignmentMatList, limProbsVec, transMatList, numOpenMP, equivVector, alignmentAlphaMatList, alignmentBinList, childNodeInClusIndic, returnMatIndic, internalFlag, priorBySizeTransMatBool) {
    .Call('DMphyClus_logLikCppToWrapV', PACKAGE = 'DMphyClus', edgeMatList, alignmentMatList, limProbsVec, transMatList, numOpenMP, equivVector, alignmentAlphaMatList, alignmentBinList, childNodeInClusIndic, returnMatIndic, internalFlag, priorBySizeTransMatBool)
}

