# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikCppToWrap <- function(edgeMat, logLimProbsVec, logTransMatList, numOpenMP, equivVector, alignmentBin, returnMatIndic, internalFlag, sitePatterns) {
    .Call('DMphyClus_logLikCppToWrap', PACKAGE = 'DMphyClus', edgeMat, logLimProbsVec, logTransMatList, numOpenMP, equivVector, alignmentBin, returnMatIndic, internalFlag, sitePatterns)
}

getConvertedAlignmentToWrap <- function(numOpenMP, equivVector, alignmentAlphaMat, sitePatterns) {
    .Call('DMphyClus_getConvertedAlignmentToWrap', PACKAGE = 'DMphyClus', numOpenMP, equivVector, alignmentAlphaMat, sitePatterns)
}

redimMultiBinByClus <- function(multiBinByClus) {
    .Call('DMphyClus_redimMultiBinByClus', PACKAGE = 'DMphyClus', multiBinByClus)
}

logLikCppToWrapV <- function(edgeMatList, logLimProbsVec, logTransMatList, numOpenMP, equivVector, alignmentBinList, returnMatIndic, internalFlag, sitePatternsList) {
    .Call('DMphyClus_logLikCppToWrapV', PACKAGE = 'DMphyClus', edgeMatList, logLimProbsVec, logTransMatList, numOpenMP, equivVector, alignmentBinList, returnMatIndic, internalFlag, sitePatternsList)
}

